version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PG_URI=postgres://postgres:iamgoingtoUSC@1@host.docker.internal:5432/echovote
      - JWT_SECRET=your_jwt_secret_key
      - EMAIL_USER=iamgod4493@gmail.com
      - EMAIL_PASS=izmo tpdm ujsv swde
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: 